### ISSUE TITLE
RequireJS?

### ISSUE THREAD

**Issue by sgentile** [gaevoy/ko.widget#1]
I have a 'legacy' knockout application, it does not use RequireJS.

Is RequireJS required for me to use your library ?

Thanks

**Comment by gaevoy** [comment]
ko.widget depends on RequireJS. 
Why is it so? Because widget can be loaded on-demand (lazy) by using RequireJS functionality.
Of cause ko.widget can be used without RequreJS but I have to do new version for it.

**Comment by gaevoy** [comment]
By the way, @sgentile how will you rewrite HelloWorldWidget (https://github.com/gaevoy/ko.widget/tree/gh-pages/demo/ver_2.0/App/HelloWorldWidget) without using RequireJS? Can you please show an example?

**Comment by gaevoy** [comment]
RequireJS dependency was removed, but you still can load ko.widget by RequireJS, so it remains amd ready.
